### ISSUE TITLE
Not create and upload

### ISSUE THREAD

**Issue by Kirill** [mfuentesg/SyncSettings#1]
* I get token. Put in config.
* Click to Create and Upload - nothing.
* Ok. Create blank gist {}. Get it id and put to config. 
* Click to Upload - I get error in status bar:
```Sync Settings: [Error 2] No such file or directory```

> Windows 7. Sublime 3

**Comment by mfuentesg** [comment]
Please open your Sublime console and attaching a screenshot when the error is occurring

**Comment by Kirill** [comment]
![2015-08-07 08_31_43](https://cloud.githubusercontent.com/assets/302940/9130005/c5e9f92c-3cde-11e5-845e-98814d0f6a4b.png)

**Comment by Kirill** [comment]
Without opacity
![2015-08-07 08_33_00](https://cloud.githubusercontent.com/assets/302940/9130021/f9a1bbba-3cde-11e5-9500-5993b7c82570.png)

**Comment by husa** [comment]
Same for me. Console output
```
Traceback (most recent call last):
  File "sync_settings.commands.create_and_upload in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package", line 27, in onDone
  File "sync_settings.sync_settings_manager in C:\Users\myUser\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package", line 38, in getContentFiles
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\myUser\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\Package Control.system-ca-bundle'
```

**Comment by mfuentesg** [comment]
Thanks @husa and @Kirill for your feedback, today i will make a new release!

**Comment by mfuentesg** [comment]
Solved!
