### ISSUE TITLE
Cannot edit the gist

### ISSUE THREAD

**Issue by alexcroox** [mfuentesg/SyncSettings#101]
> [16/05/2018 - 08:24:47] ERROR: [Cannot edit the gist] - Code 404 - Not Found, File: /Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist_api.py - Line: 88

Same error when trying to create new gist `[Gist cannot created]`

I've tried removing the plugin and re-installing. Anything else I can try?

**Comment by nesshoever** [comment]
Same problem here. What I found is that during installation of the package, there is a folder called "requests" created at "%APPDATA%\Sublime Text 3\Packages" instead of the expected "Sync Settings".
That folder contains some generic template files and folders

**Comment by mfuentesg** [comment]
@alexcroox, @nesshoever i was working to fix this issue, soon i will release a new version.

Let me know, if you are experimenting the error again.

**Comment by alexcroox** [comment]
Updated to latest version, same issue I'm afraid. Even tried Create and Upload.

**Comment by alexcroox** [comment]
```[06/02/2019 - 15:51:27] ERROR: [Gist cannot created] - Code 404 - Not Found, File: /Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package/sync_settings/libs/gist_api.py - Line: 61
```

**Comment by mfuentesg** [comment]
Hey Alex, you are not using the latest version. Because that file (gist_api.py) does not exists anymore.

Try to reinstall it


https://github.com/mfuentesg/SyncSettings/blob/master/sync_settings/libs/gist.py

**Comment by mfuentesg** [comment]
@alexcroox please, reopen this issue if you are  still experiencing the issue.

**Comment by nesshoever** [comment]
I cannot reopen the ticket, but this 'request' folder is still created and the settings file is completely empty, so I wouldn't know how to format the settings file to enter gist id and token

**Comment by alexcroox** [comment]
@mfuentesg strange I updated it before I posted:

![img](https://cl.ly/ced49a945f85/Screenshot%202019-02-07%20at%2009.33.18.png)

I'll try a re-install
