### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by sammcj** [mfuentesg/SyncSettings#102]
Firstly thank you for this wonderful plugin, I've been using it for a long time - it's been very useful and I have never had problems with it syncing around my 4 machines.

Question time,

On the [Sublime Packages site, it shows this package as '[Unmaintained]'](https://packagecontrol.io/packages/Sync%20Settings).

* Is it really unmaintained, I can see there were commits just 3 days ago?
* If so, why (was it just too much work, is there a better plugin to use for some reason, just CBF with issues / MRs) any reason is fine, a few of us would just like to know.

Thanks :)

**Comment by marsjaninzmarsa** [comment]
> Is it really unmaintained, I can see there were commits just 3 days ago?

Yeah, 3 days ago there was a commit 98a7308, adding mentioned _Unmaintained_ tag. It was sole activity in repo since Aug 17, 2017.

**Comment by sammcj** [comment]
Oh, I should have looked at the commit, that's really sad to hear.

What are people using now?

**Comment by marsjaninzmarsa** [comment]
> What are people using now?

This one. Works fine, even if unmaintained.

**Comment by sammcj** [comment]
I agree but I suspect it’ll get removed as part of cleanup at some point?

--
Sam McLeod

**Comment by marsjaninzmarsa** [comment]
Why should it?

**Comment by mfuentesg** [comment]
@sammcj i really appreciate your words, but right now i don't have time to maintain this repo.
