### ISSUE TITLE
Wrong network error

### ISSUE THREAD

**Issue by BoberMod** [mfuentesg/SyncSettings#113]
I have specified token in the user settings file. When I try to "_Create and Upload_", I get an network error.
![image](https://user-images.githubusercontent.com/8740496/52526676-e3e29400-2cc4-11e9-8a26-1d6ecd44ce75.png)
I tried to specify `gist_id`, then upload/download, but same error. Also tried with https proxy, but it didn't help.

Log file (`sync.log`) is empty.
**OS:** Windows 10 x64
**Sublime-text version:** 3.1.1 (build 3176)

**Comment by mfuentesg** [comment]
That error only happens when a connection error was catch , are you using the latest version of the plugin ?

**Comment by BoberMod** [comment]
> That error only happens when a connection error was catch , are you using the latest version of the plugin ?

Yes, installed from https://packagecontrol.io/packages/Sync%20Settings and tried to install the latest version from github (releases).

**Comment by mfuentesg** [comment]
Please, let me know if are experiencing the same issue.
i will close it for now.

**Comment by BoberMod** [comment]
> Please, let me know if are experiencing the same issue.
![image](https://user-images.githubusercontent.com/8740496/52844478-59a78f00-310d-11e9-8f2a-804815a1ec4c.png)
"log" from sublime console https://hastebin.com/vovoyisogu.py

**Comment by mfuentesg** [comment]
@BoberMod are you using a proxy?

**Comment by BoberMod** [comment]
> @BoberMod are you using a proxy?

No
```
    // An HTTP proxy server to use for requests.
    "http_proxy": "",

    // An HTTPS proxy server to use for requests.
    "https_proxy": "",
```

**Comment by mfuentesg** [comment]
apparently you have a lot of issues with ssl, check your log file. because, sync settings is not the unique one.
