### ISSUE TITLE
Ignore certain settings

### ISSUE THREAD

**Issue by dawhum** [mfuentesg/SyncSettings#126]
We're looking to use Sync Settings to share the Sublime configuration across a team, and it'd be brilliant if it could be configured to ignore certain settings, e.g. the font size.

Hooks would be an alternative solution to this: https://github.com/mfuentesg/SyncSettings/issues/104

**Comment by mfuentesg** [comment]
hey, this is very customized my idea is keep a general solution to upload your settings.

i will try to implement hooks soon, but i am very busy in this time.

**Comment by mfuentesg** [comment]
Closing this issue, because it is out of the scope of this plugin.
