### ISSUE TITLE
SSL certificate_verify_failed

### ISSUE THREAD

**Issue by vv0rk** [mfuentesg/SyncSettings#128]
when I try upload / download settings, I has error from Sync Settings: Can't perform this action due to network errors. reason: [SSL; CERTIFICATE_VERIFY_FAILED] cetrificate verify failed (_ssl.c:548)

what I can do to resolve the error?
[sync.log](https://github.com/mfuentesg/SyncSettings/files/3275116/sync.log)

**Comment by mfuentesg** [comment]
Apparently you are using an untrusted certificate. (This error is raised by requests package).

Please. feel free to reopen this issue if you are still facing it.
