### ISSUE TITLE
Unable to download settings from my publicly available gist

### ISSUE THREAD

**Issue by rousnay** [mfuentesg/SyncSettings#129]
My settings: 
`{
 "gist_id": "https://gist.github.com/rousnay/2214f59b5ba87f27f4e15a787d8a0759"
}`

And the log below:

> WARNING:Sync Settings.sync_settings.libs.logger:{'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
> ERROR:Sync Settings.sync_settings.libs.logger:The requested gist do not exists, or the token has not enough permissions
> Traceback (most recent call last):
>   File "C:\Users\Md Mozahidur Rahman\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/commands/download.py", line 46, in download
>     ).get(settings.get('gist_id'))
>   File "C:\Users\Md Mozahidur Rahman\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 46, in with_gid_wrapper
>     return func(self, *args, **kwargs)
>   File "C:\Users\Md Mozahidur Rahman\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 83, in get
>     return self.__do_request('get', self.make_uri(gid)).json()
>   File "C:\Users\Md Mozahidur Rahman\AppData\Roaming\Sublime Text 3\Installed Packages\Sync Settings.sublime-package\sync_settings/libs/gist.py", line 98, in __do_request
>     raise NotFoundError('The requested gist do not exists, or the token has not enough permissions')
> Sync Settings.sync_settings.libs.gist.NotFoundError: The requested gist do not exists, or the token has not enough permissions

**Comment by mfuentesg** [comment]
gist_id must be set as `2214f59b5ba87f27f4e15a787d8a0759`
