### ISSUE TITLE
Saving Access Token

### ISSUE THREAD

**Issue by adtya9876** [mfuentesg/SyncSettings#132]
When tring to save my access token to the user setting this error presits:

> Error trying to parse setting: Unexpected trailing characters in Package\User\SyncSettings.sublime-settings:1:15
![suberr](https://user-images.githubusercontent.com/31375056/61905423-ac9c3280-af46-11e9-9f1a-360259c1a047.png)

**Comment by mfuentesg** [comment]
What is the file content?

**Comment by mfuentesg** [comment]
closed by insufficient information
