### ISSUE TITLE
User keymaps not synced - when missing packages

### ISSUE THREAD

**Issue by ipstone** [mfuentesg/SyncSettings#134]
Hello,

Recently I ran into sublime syncsetting not working for my keymap to sync - and found out the cause is due to the unfinished syncing process, as there are obsolete packages on one machine (no longer available on package control).

Might we add a message for 'uncompleted syncing' and giving the possible cause of the failed sync?

Another suggestion would be to change the order of things being synced - keymap is probably move to higher priority on the list (second to user setting), as it really affects user experience/habit when using a new machine.

Many thanks for the work on this very useful plugin!

**Comment by mfuentesg** [comment]
So sorry the mega delay, but, are you still facing this issue?
