### ISSUE TITLE
Save `.sync_settings` in `.config`

### ISSUE THREAD

**Issue by muuvmuuv** [mfuentesg/SyncSettings#135]
In my opinion this folder belongs more to `.config/Sublime text/extensions/sync_settings` or somewhere else than in my users root dir. I#m that type of person that loves to have everything organized 😁. Would like to hear your opinion on this.

FYI: Most configs are stored there e.g. Enpass and macOS Configstore.

**Comment by mfuentesg** [comment]
Let's try to add a new configuration in `.sublime-settings` file to give you the flexibility to set any folder for config.

Should be great if you can raise a PR for it!

**Comment by muuvmuuv** [comment]
Not much time currently. It isn't mandatory, just my inner Monk.

**Comment by mfuentesg** [comment]
I won't implement this feature for now
