### ISSUE TITLE
Getting permission error

### ISSUE THREAD

**Issue by hgsadhrakiya** [mfuentesg/SyncSettings#139]
Hello,
I am getting this error while using this command: 
Sync Settings: Download

"sync settings: the requested gist do not exist or the token has not enough permissions"

Can you please guide me on this?

**Comment by elie464** [comment]
Try `{"gist_id": "<gist_id>"}` without the https://etc.

**Comment by daniele-niero** [comment]
For what it's worth, the suggestion above worked for me. I'm on Ubuntu 18.04.4 LTS, on an old Mac book pro (2009/2010)

**Comment by marcovirtual** [comment]
> Try `{"gist_id": "<gist_id>"}` without the https://etc.

This worked for me too. Remember to delete the .`js` file extension from the `gist_id` when you copy it from GitHub.

**Comment by TheSecEng** [comment]
@hgsadhrakiya any update on this?

**Comment by mfuentesg** [comment]
Gist id is just the last part the Gist URL. 
i.e `https://gist.github.com/user/86ee9288b05d236dada81148f66db8db` id = `86ee9288b05d236dada81148f66db8db`.
