### ISSUE TITLE
On Mac OS, download puts files in ~ /.sync_settings/temp

### ISSUE THREAD

**Issue by Guava-de-Boston** [mfuentesg/SyncSettings#140]
On a Mac (running Mojave, MacOS 10.14.6) executing Sync Settings: Download puts the files from the target github gist into ~/.sync_settings/temp . I was expecting these would be dumped to the Sublime Text 3 ./Packages/User subdirectory.

Q: is this expected behavior on a Mac? (I have not tried this on a linux box yet.)
Q: if this _is_ expected behavior, then perhaps there needs to be some documentation to clarify that the user needs to copy the downloaded files to the ./Packages/User subdir.
Q: is there a config value to direct Sync Settings to use a different download subdirectory?

Note: the download occurs without error; and the sync settings log is empty.

**Comment by mfuentesg** [comment]
It is the expected behavior, this folder is used as temporary folder, all files will be moved to the user folder.

**Comment by RobinWest** [comment]
I am having this exact issue. What triggers them to be moved to the User folder? Mine are not being moved.

I'd also note the downloaded files are encoded too, so assume they need to be unencoded before being moved.

**Comment by mfuentesg** [comment]
This is not an issue, temp folder is used by SyncSettings in order to download current version from remote server (Gist) and then use them, to replace your current files in your computer.

**Comment by RobinWest** [comment]
I have no problem with the temp folder, my problem is that they are NOT being moved into my User folder afterwards.
