### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by carlesba** [mfuentesg/SyncSettings#17]
I did:

1. Generate token and put it in editor 1
2. Create Gist and put it in editor 1
3. Create and update (it updated the first gist I put)
4. Generate new token and put it in editor 2
5. Add gistId in editor 2
6. Download

Last step broke all my config in editor 2 and didn't put settings from editor 1

**Comment by mfuentesg** [comment]
Hi Carles, i am working on this bug, now all files are downloaded in one step.
This action not validates that the plugin was before installed.

Issue https://github.com/mfuentesg/SyncSettings/issues/12

**Comment by mfuentesg** [comment]
Closed by Issue #12
