### ISSUE TITLE
Unicode caracter latin-1

### ISSUE THREAD

**Issue by uberkael** [mfuentesg/SyncSettings#171]
I'm getting this error when I upload the config

![image](https://user-images.githubusercontent.com/1783926/85907617-57ca0180-b812-11ea-90fe-76a7bf6583f5.png)

I can't locate where is the character error only with that information.

Thanks

**Comment by mfuentesg** [comment]
@uberkael are you using latest version of the plugin?

**Comment by uberkael** [comment]
It's weird, the problem is now gone...
It happened after the last update but it seems to work now as normal.
