### ISSUE TITLE
JSON decode error if URL in sublime-settings file

### ISSUE THREAD

**Issue by hans00** [mfuentesg/SyncSettings#177]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: Any
 - Sublime Version 3

**Log file content with debug property in true**

My settings file has URL string. Use download, it's alert JSON decode error.

**Comment by dotiful** [comment]
confirm this issue

**Comment by mfuentesg** [comment]
@hans00 @dotiful i have created a new version of sync settings, in few minutes/hours (depending of package control release checker) you should be able to use sync settings normally. 

Please feel free to reopen this issue if you still face it.
