### ISSUE TITLE
Including SyncSettings in sync

### ISSUE THREAD

**Issue by mtheos** [mfuentesg/SyncSettings#180]
~~I'm trying to include SyncSettings.sublime-settings as part of my sync.~~

~~I tried adding it as `"included_files": [ "SyncSettings.sublime-settings" ]` but it doesn't upload it.~~

**Comment by mtheos** [comment]
Just realized gists can be secret but not private. Best not to upload my access token.

**Comment by mfuentesg** [comment]
This is intentional, i am excluding SyncSettings.sublime-settings file all the time just to avoid sharing access token

**Comment by mtheos** [comment]
Yes, this feature would require a rework to use a private settings repository instead of a gist.

Not sure if there's any demand for it beyond me.
