### ISSUE TITLE
Error when trying to create and upload my settings.

### ISSUE THREAD

**Issue by havilson** [mfuentesg/SyncSettings#182]
Hi, I'm using ST3 in Windows 10 and just installed your plugin. I'm willing to sync between Windows and Linux installations.
Follow the instructions to create a token and used it inside my user settings as written.
When I tried to Create and Upload for the 1st time I got the following error message:
"Sync Settings:
load_verify_locations() takes at most 2 arguments (3 given)"

When I opened the log file nothing was inside.

**Comment by havilson** [comment]
Just an update.
I modified my settings and now I got another kind of error.

Here's my sync.settings user settings:
{
    "access_token": "1234567890987654321",
    "gist_id": "1234567890987654321"
}

Now this is the error that I got when I try to use Sync settings plugin:
"Sync Settings:
Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\xxxxxx\AppData\Roaming\Sublime Text 3\Installed Packages\CodeTime.sublime-package\vendor\certifi\cacert.pem"

**Comment by mfuentesg** [comment]
It is sounds like an issue created by CodeTime, and it is overwriting path for certificates

**Comment by havilson** [comment]
Well, I'll take CodeTime out.

**Comment by mfuentesg** [comment]
Cool, closing.
