### ISSUE TITLE
[Feature Request] Allow ignoring folders

### ISSUE THREAD

**Issue by Daggy1234** [mfuentesg/SyncSettings#191]
I use different machines and I would not like to commit any files from `Packages/` or `linters/`. Atm there is no way to add this functionality. Perhaps an `ignore_directory` entry in the Json?

**Comment by mfuentesg** [comment]
Sync Settings provides an option whose aim is to ignore files, using wilcards. This option is `excluded_files`. Take a look to this section in the [readme file](https://github.com/mfuentesg/SyncSettings#options).

i.e
```json
{
  "excluded_files": [
    "linters/**/*.*"
  ]
}
```

**Comment by Daggy1234** [comment]
Oh my bad thanks
