### ISSUE TITLE
How to avoid syncing disabled extensions as uninstalled extensions?

### ISSUE THREAD

**Issue by snowman** [mfuentesg/SyncSettings#195]
Reproduce
===
First, try to disable one extension then upload settings, and this results in deletions in file `extensions.json`, same as when you uninstall an extension.

Expected
===
I want to back up all installed extensions, including disabled extensions.

**Comment by mfuentesg** [comment]
Could you tell if this file `extensions.json` is included in the latest version of ST?

**Comment by snowman** [comment]
Sorry, I confused this repos with https://github.com/shanalikhan/code-settings-sync 😅😅😅

**Comment by mfuentesg** [comment]
hahah, don't worry, both plugins have the same purpose, this one is for Sublime Text.

Happy coding!
