### ISSUE TITLE
Sublime Text Sync Settings not syncing whichever file we wish to be synced, when specified in "included_files" settings

### ISSUE THREAD

**Issue by vivek1986** [mfuentesg/SyncSettings#199]
I have Windows 10 64Bit OS and under it Sublime Text 4 (4113) installed. And I recently came across and installed [Sync Settings](https://packagecontrol.io/packages/Sync%20Settings).

Now I have tried to specify the correct name and/or full-path of Sync Settings JSON file itself to be synced whenever Sync Settings: Upload the command is explicitly ran, but it doesn't sync the "extra" file that I have specified and only syncs the usual files that it does by default settings.

Below is my "Sync Settings'" settings file:
`{
    "auto_upgrade": true,
    "gist_id": "<gistID>",
    "access_token": "<token>",
    "excluded_files": [
        "*.dmg",
        "*.DS_Store*",
        "*.exe",
        "*.Spotlight-V100",
        "*.Trashes",
        "*ehthumbs.db",
        "*oscrypto-ca-bundle.crt",
        "*Package Control.cache/*",
        "*Package Control.last-run",
        "*Package Control.merged-ca-bundle",
        "*Package Control.system-ca-bundle",
        "*Package Control.user-ca-bundle",
        "*Thumbs.db"
    ],
    "included_files": [
        "SyncSettings.sublime-settings"
    ]
}`

I've also tried giving the full-path of settings file like `"included_files": [ "C:\\Users\\<Username>\\AppData\\Roaming\\Sublime Text\\Packages\\User\\SyncSettings.sublime-settings" ],` but it just doesn't work and gives error: Unable to open /C/Users/\<Username\>/AppData/Roaming/Sublime Text/Packages/Sync Settings/SyncSettings.sublime-settings. Can anyone help ?

**Note:** I have created a secret gist, so I ain't worried about token and gistId being saved online in gist...

**Comment by xinxilas** [comment]
Im ivestigating it too, i want to make my custom files 

maybe i want only keybind and settings file

**Comment by mfuentesg** [comment]
Hi, `SyncSettings.sublime-settings` is not included by default in the application in order to avoid collisions in your current machine and the one you want to synchronize.

**Comment by vivekwebm2020** [comment]
Ok, if I still  wanna include it then is there any possible way ? Even a backdoorish/hackish way also will be fine as long as it does sync that SyncSettings file, because I feel, if what I want to sync cannot be stored on cloud (Github is cloud here) then it kinda loses the point...

**Comment by mfuentesg** [comment]
Sorry, but it is not possible. If you want a hacky way is cloning this project into the Users folder of ST and then restart it to enable the plugin from source code .

Then remove this part of the code `p.extend(['*SyncSettings.sublime-settings'])`  in order to avoid the exclusion. https://github.com/mfuentesg/SyncSettings/blob/90403241f41f312f7cf073cad2f8b227934c4ed5/sync_settings/sync_manager.py#L31-L40

By design I prefered to ignore this file just to avoid unnecessary collisions and thus keep indepedent configurations by machine.

**Comment by vivekwebm2020** [comment]
@mfuentesg Thanks a lot, that helped fix this... :)
