### ISSUE TITLE
Packages are not downloaded and installed - should they be?

### ISSUE THREAD

**Issue by benfrain** [mfuentesg/SyncSettings#31]
I'm not sure if SyncSettings should be doing this or not. 

When I run `sync-settings: download` it does it's thing. However, even after a restart, packages that are one instance of Sublime are not installed on the current one.

For example, at work I have 'AceJump' installed and have created a sync-settings upload there. However, when I run `sync-settings: download` on my home computer (which doesn't yet have AceJump installed) and restart Sublime, AceJump doesn't get installed. 

Should this package handle sync and install of packages – or it is merely settings?

**Comment by mfuentesg** [comment]
Hi Ben,

Sync Settings just sync the settings files.
If the sync process include the package control settings file and found a package that is not installed package control will install it automatically.

**Comment by benfrain** [comment]
Hi, I have not amended the default settings. Do I need to pass the package-control settings file into the config in order for the sync-settings to see it?

**Comment by mfuentesg** [comment]
can you paste here the content of the logs file?

Execute `Sync Settings: Show Logs` command

**Comment by benfrain** [comment]
Hi sure (mangled the token ID):

````
[11/01/2016 - 23:49:20] INFO: You need set the access token
[11/01/2016 - 23:54:56] INFO: Gist created, id = 8780ce613bXXXXXXXX
[11/01/2016 - 23:55:02] INFO: Gist id updated successfully!
[13/01/2016 - 21:13:29] INFO: Files Downloaded Successfully. Please restart Sublime Text to install all dependencies!.
[18/01/2016 - 11:55:55] INFO: Files Downloaded Successfully. Please restart Sublime Text to install all dependencies!.
````

**Comment by mfuentesg** [comment]
It is not neccesary add the package control settings file to the configuration.

**Comment by benfrain** [comment]
OK, so should this have worked?

**Comment by mfuentesg** [comment]
Yup

**Comment by benfrain** [comment]
Ok. Is there anything else you need me to do to ascertain whether this is an actual bug?

**Comment by mfuentesg** [comment]
Can you check in `PackageControl` settings file, if is included your lost package (`a.k.a AceJump`) after download your settings file with `SyncSettings`?

**Comment by benfrain** [comment]
Hi, no, this is all I got:

````
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"Autoprefixer",
		"BracketHighlighter",
		"CSS3",
		"Emmet",
		"Expand Selection to Quotes",
		"Fix Mac Path",
		"Gulp",
		"HTML-CSS-JS Prettify",
		"MarkdownEditing",
		"Package Control",
		"PackageResourceViewer",
		"Predawn",
		"SideBarEnhancements",
		"SublimeLinter",
		"SublimeLinter-contrib-stylelint",
		"SublimeLinter-contrib-tslint",
		"SublimeLinter-jshint",
		"Sync Settings",
		"Syntax Highlighting for PostCSS",
		"TypeScript"
	]
}


````
