### ISSUE TITLE
Doesn't seem to work on multiple devices

### ISSUE THREAD

**Issue by dtunes** [mfuentesg/SyncSettings#33]
I've got it working on one machine, then tried on a different machine, tried with different and the same auth tokens and still no go.

When using Sync Settings: Download, I get the message on the status bar saying that the files have been downloaded and to restart Sublime, after doing so, it seems that even Sync Settings is removed and no settings come across from the gist.

**Comment by mfuentesg** [comment]
Thanks for your feedback, i will review that.

tell me, which are your os's and the sublime text versions?

**Comment by mfuentesg** [comment]
You can paste here the console output after execute the download command?

**Comment by dtunes** [comment]
Mac OS X at home and work, also tried on another work machine with Windows 10.

Sublime text 3 in all machines.

**Comment by dtunes** [comment]
Hi,

fresh install on the windows machine, installed Sync Settings and added token etc. When doing a Sync Download, this is what I get.

'charmap' codec can't encode character '\x80' in position 0: character maps to <undefined>
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings

But, on the first machine which I created the gist with in the first instance, it syncs fine, here's the output.

'ascii' codec can't encode character '\x80' in position 0: ordinal not in range(128)
reloading Packages/User/Git.sublime-settings
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/SublimeLinter.sublime-settings
reloading Packages/User/trailing_spaces.sublime-settings
reloading Packages/User/WakaTime.sublime-settings

As you can see, not all files get copied on the Windows machine, some encoding error, might not be anything to do with your plugin which by the way, its awesome.

Copying the contents of the files above on their respective files on Sublime on the Windows machine and then trying to sync seems to work, I've tried the same approach on the Mac at home and it works if you manually copy the contents over, then syncing after that seems to work fine.

**Comment by dtunes** [comment]
did you manage to replicate this problem? not sure if it is something related to your plugin or not... Can you offer anything?
