### ISSUE TITLE
only support path： Sublime Text 3\Data\Packages\User

### ISSUE THREAD

**Issue by kumiao** [mfuentesg/SyncSettings#36]
only support path： Sublime Text 3\Data\Packages\User
but i want sync the file in path：Sublime Text 3\Data\Packages\HTML-CSS-JS Prettify\ .jsbeautifyrc

what should I do？

**Comment by mfuentesg** [comment]
By default, the plugin upload all files inside the User folder. Any other path will be ignored.

But, this can be a new feature, extending the `included_files` option.
