### ISSUE TITLE
having an issue, package seems to be broken

### ISSUE THREAD

**Issue by Place1** [mfuentesg/SyncSettings#38]
using any command results in an error like this:

[14/06/2016 - 22:49:49] ERROR: [Gist can't created] - Code 404 - Not Found, File: sync_settings.libs.gistapi in /Users/James/Library/Application Support/Sublime Text 3/Installed Packages/Sync Settings.sublime-package - Line: 39

not really sure what's going on. I installed via package control.

**Comment by mfuentesg** [comment]
Are you trying to create an Gist?

**Comment by hubplace1** [comment]
Yeah I had my access token in the config. 
I manually created a gist and put the id in the config as well and nothing seemed to work. Perhaps my config is wrong? Could you post an example config maybe (if you think that's the issue)

**Comment by Place1** [comment]
Oops. The above is me.

**Comment by mfuentesg** [comment]
https://github.com/mfuentesg/SyncSettings/blob/master/SyncSettings.sublime-settings

This file has the available settings

**Comment by Place1** [comment]
Yep cool, that's what i was using. Nothing works with this config
{
	"access_token": "<<my access token>>",
}

and nothing works with this either
{
	"access_token": "<<my access token>>",
	"gist_id": "<<gist id for gist i manually created>>"
}

**Comment by mfuentesg** [comment]
Okay, give me some of time now i do not have sublime.

**Comment by mfuentesg** [comment]
Thanks for the report

**Comment by mfuentesg** [comment]
Soon a new version! ;)
