### ISSUE TITLE
if `auto_upgrade` is true, will only download ?

### ISSUE THREAD

**Issue by ark-tds** [mfuentesg/SyncSettings#41]
If `auto_upgrade` is true, whether SyncSettings will automatically only download a new settings on Gist to ST ? or only upload a new settings on ST to Gist ? or both download and upload ?

**Comment by mfuentesg** [comment]
Hi,

The auto_upgrade just download the latest settings on your gist!

**Comment by ark-tds** [comment]
I got it.
Thanks for rewriting README.md 😄

**Comment by mfuentesg** [comment]
No problem!
