### ISSUE TITLE
downloading append a newline in configfile

### ISSUE THREAD

**Issue by imbubble** [mfuentesg/SyncSettings#45]
- Arch Linux 4.6.4-1-ARCH x86_64
- ST3 build3114
- SyncSettings 2.3.1
- Python 3.5.2

i have a file named `config_file1` was uploaded. but every time run `Sync Settings: download`, a newline is appended. with time `Sync Settings: upload`s and `Sync Settings: download`s makes lots of newlines append.

**Comment by mfuentesg** [comment]
Hey @imbubble thanks for your comment
I will review this issue ;)

**Comment by mfuentesg** [comment]
Fixed #49
