### ISSUE TITLE
Not able to exclude arbitrary files

### ISSUE THREAD

**Issue by heimpogo** [mfuentesg/SyncSettings#51]
It would be great if it would be possible to exclude  arbitrary files. In my case I have problems with cache files created by Package Control that are named `Package%20Control.cache%2F01524fae79697630d0454ba3fabd9414` or similar.
Excluding them by  extension does not work. I'm afraid I need wildcards for these.

**Comment by mfuentesg** [comment]
which is the full path to that file?

**Comment by mfuentesg** [comment]
https://docs.python.org/3/library/fnmatch.html
