### ISSUE TITLE
oscrypto-ca-bundle.crt, Build 3126

### ISSUE THREAD

**Issue by tomahl** [mfuentesg/SyncSettings#59]
Hi,

SyncSettings v.2.4.0

I can't recall the the file named "oscrypto-ca-bundle.crt" has been synced before and according to this [post](https://forum.sublimetext.com/t/generating-oscrypto-ca-bundle-crt-after-mac-os-install-and-security/23020) it doesn't sound like it should either. Maybe you could put it in the default "excluded_files"?

**Comment by mfuentesg** [comment]
Thanks @tomahl , you are welcome to create a new Pull Request with your changes
