### ISSUE TITLE
Litle improvement in the docs

### ISSUE THREAD

**Issue by aarongarciah** [mfuentesg/SyncSettings#60]
Hi! This package absolutely rocks! A huge improvement in the workflow for many users as myself. I noticed one thing that maybe other users come across sometime. If you provide in the configuration file a public _gist_id_, GitHub will revoke the _access_token_ provided in the config file after one use due to security concerns. Would be nice to specify this issue in the [docs](https://packagecontrol.io/packages/Sync%20Settings?__s=wgnjrs6brfsbdjvoda7h) and recommend the user to provide a private _gist_id_.

Thank you!

PS: find attached the email received.
![github-revoked-token](https://cloud.githubusercontent.com/assets/7225802/18948749/9edd65ae-8638-11e6-9a66-13c93d8e83e4.jpg)

**Comment by mfuentesg** [comment]
Thanks @aarongarciah , by security the plugin creates a secret Gist ignoring gist visibility

**Comment by aarongarciah** [comment]
Hi @mfuentesg. I misunderstood, I thought that the _gist_id_ was required. Maybe specifying that this option is not required because the Package will create a gist automatically is a good idea.

Thanks!
