### ISSUE TITLE
Doubt about the component configuration

### ISSUE THREAD

**Issue by erlonpr** [mfuentesg/SyncSettings#70]
I have the following question:

After paste the token in the session "User Settings", I click save, but the Sublime Text 3 returns me the following error: "Error trying to parse settings: Expected value in Packages\User\SyncSettings.sublime-settings:1:1"
What should I do to solve the problem?

**Comment by mfuentesg** [comment]
Your File should to have the following structure:

```json
{
  "access_token": "<YOUR_ACCESS_TOKEN>"
}
```

The following error is triggered by **Package Control**, when the file has not a valid format, like:

```json
{
  "INVALID_FORMAT"
}
```

![captura de pantalla 2016-10-26 a la s 20 52 39](https://cloud.githubusercontent.com/assets/8986996/19749257/2ec22f98-9bbe-11e6-88a5-c6dc4f4d5bf4.png)

**Comment by erlonpr** [comment]
Thanks a lot for the help, my friend.

Em qua, 26 de out de 2016 22:00, Marcelo Fuentes <notifications@github.com>
escreveu:
