### ISSUE TITLE
Cannot download,upload

### ISSUE THREAD

**Issue by dtunes** [mfuentesg/SyncSettings#72]
![image](https://cloud.githubusercontent.com/assets/1164234/20248135/464ef960-aa42-11e6-8688-33d32178c373.png)

Tried deleting the package and reinstalling it after restarting Sublime, still no go. It doesn't even outputs anything into the logs file.

Internet is working fine, started happening last week.

Anyone experiencing the same issue?

**Comment by mfuentesg** [comment]
Paste here the log file content

**Comment by dtunes** [comment]
I would've, but as I stated above, it doesn't even touch the log file...
![sublime-error](https://cloud.githubusercontent.com/assets/1164234/20507545/268d6e52-b0c0-11e6-8f96-a4320655f5fe.gif)

As you can see, the error doesn't output anything into the logs file.

I've also tried at home "on a different computer" still no go.

**Comment by mfuentesg** [comment]
It is very weird, is the console also empty?

**Comment by dtunes** [comment]
Just confirmed, no nothing.. I've tried uninstalling/reinstalling Sync Settings, still no go. I'll try to reinstall Sublime and hopefully that will get rid of the issue.

**Comment by dtunes** [comment]
Ok,

reinstalling didn't work. I then removed everything from Sublime's folder and started from scratch, packagecontrol, SyncSettings and kept installing and testing after that.

I think I found the package that was causing it. https://packagecontrol.io/packages/sublime-github.

After installing that package and restarting sublime, same issue happened, removing the package and restarting, the issue goes away.

**Comment by mfuentesg** [comment]
Hey @dtunes i will try to install that package and test the bug

**Comment by mfuentesg** [comment]
Hey @dtunes i think that your error is raised by this issue

https://github.com/bgreenlee/sublime-github/issues/89

**Comment by mfuentesg** [comment]
@dtunes `sublime-github` is the problem

**Comment by mfuentesg** [comment]
Please close this issue and creates new a on the correspondent package.

Thanks!
