### ISSUE TITLE
"Package%20Control.sublime-settings" instead of "Package Control.sublime-settings"

### ISSUE THREAD

**Issue by advancid** [mfuentesg/SyncSettings#73]
Hello,

I like this package but it generates the file "Package%20Control.sublime-settings" instead of "Package Control.sublime-settings". Maybe it is the API which does this? Or maybe it is [this line](https://github.com/mfuentesg/SyncSettings/blob/master/sync_settings/sync_manager.py#L100)?

[Here](https://gist.github.com/advancid/d0bf709230aaf3316368db971912c5df) is a gist that the plugin generated for me.

**Comment by dtunes** [comment]
Are you having problems with SyncSettings because of this? I checked mine and the the file name on my gist is the same as yours, but when it syncs it must be converting the %20 to space.

**Comment by mfuentesg** [comment]
Hi @advancid , this is the unique way to upload files with special chars like spaces. When the files are downloaded the special chars are replaced.
