### ISSUE TITLE
How to remove a unavailable package

### ISSUE THREAD

**Issue by emamut** [mfuentesg/SyncSettings#74]
I love the work you did in this plugin but I have the following message each time I open Sublime. What can I do to remove?

![captura de pantalla de 2016-11-24 10 33 08](https://cloud.githubusercontent.com/assets/134828/20603868/81066db2-b231-11e6-82d8-1a374d126a6b.png)

**Comment by mfuentesg** [comment]
Hey @emamut , you can edit manually the `Package Control.sublime-settings` file, remove the package reference and upload the new file version.

**Comment by emamut** [comment]
Thanks!
