### ISSUE TITLE
Error "The entered token is invalid"

### ISSUE THREAD

**Issue by fabioperrella** [mfuentesg/SyncSettings#78]
Hi, I'm trying to upload my settings but every time I'm receiving the error `The entered token is invalid`

I created a token in github with full access to everything!

Here is the log:
```
[07/12/2016 - 09:07:05] ERROR: [The entered token is invalid] - Code 401 - Bad credentials, File: sync_settings.libs.gist_api in /home/fabio/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package - Line: 24
```

Is this a bug?

What can I do to debug it if not?

**Comment by mfuentesg** [comment]
Your `access_token` is invalid or not exists, create a new `access_token` in github.

https://github.com/settings/tokens/new

**Comment by fabioperrella** [comment]
I've tried to create again, but I got the same error!

This is my token:

![image](https://cloud.githubusercontent.com/assets/302303/20992647/98ac1cfa-bccc-11e6-9a98-96ce8bab88fd.png)

If you want, I can send you in a message to you debug

**Comment by mfuentesg** [comment]
Send the access token to my email `marceloe.fuentes@gmail.com`

**Comment by fabioperrella** [comment]
I installed the plugin again in PC at home and it worked! (the error was happening in my PC at office)

I will close the issue, if it happens again, I open it again.

Thank you!

**Comment by fabioperrella** [comment]
Today I tested in PC at work using the same configuration as I used in my PC at home and the error happened again! Do you have any suggestion how to debug it?

**Comment by mfuentesg** [comment]
Send the access token to my email marceloe.fuentes@gmail.com

**Comment by mfuentesg** [comment]
I can't reproduce your error :(, paste here the content of

* `Package Control.sublime-settings`
* `.sync_settings.log`
* `.sync_settings.cache`

**Comment by fabioperrella** [comment]
Where can I find these files?

**Comment by fabioperrella** [comment]
Hi,

I looked the source code and I did the same request as is done [here](https://github.com/mfuentesg/SyncSettings/blob/0bbfa2491d5db80fc2259a43088c58119daa1c34/sync_settings/libs/gist_api.py#L21)

```
fabio@perrellalw:~ $ curl -kv "https://api.github.com/user?access_token=ce0b22cfa4ba72266ad6aa1f8cd9201a34487729"
{
  "login": "fabioperrella",
  "id": 302303,
  "avatar_url": "https://avatars.githubusercontent.com/u/302303?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/fabioperrella",
  "html_url": "https://github.com/fabioperrella",
  "followers_url": "https://api.github.com/users/fabioperrella/followers",
  "following_url": "https://api.github.com/users/fabioperrella/following{/other_user}",
  "gists_url": "https://api.github.com/users/fabioperrella/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/fabioperrella/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/fabioperrella/subscriptions",
  "organizations_url": "https://api.github.com/users/fabioperrella/orgs",
  "repos_url": "https://api.github.com/users/fabioperrella/repos",
  "events_url": "https://api.github.com/users/fabioperrella/events{/privacy}",
  "received_events_url": "https://api.github.com/users/fabioperrella/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Fabio Perrella",
  "company": "Locaweb",
  "blog": null,
  "location": "São Paulo",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 29,
  "public_gists": 8,
  "followers": 30,
  "following": 2,
  "created_at": "2010-06-10T22:58:33Z",
  "updated_at": "2016-12-20T10:41:59Z"
}
```

But when trying to upload the settings, the error still the same!

The error in log file:
```
[03/01/2017 - 08:22:43] ERROR: [The entered token is invalid] - Code 401 - Bad credentials, File: sync_settings.libs.gist_api in /home/fabio/.config/sublime-text-3/Installed Packages/Sync Settings.sublime-package - Line: 24
```

It seems the plugin is not using my key to do this request, but I am not sure. I tryed to intercept the http request using charles proxy, but I coudn't, because it is a https request.

Could you add (or how can I add) a log to be sure of what URL the plugin is trying to request?

**Comment by fabioperrella** [comment]
I restarted sublime and it is working! I think the problem can be some cache anywhere
