### ISSUE TITLE
Include SyncSettings.sublime-settings to exclude folders as default?

### ISSUE THREAD

**Issue by fabioperrella** [mfuentesg/SyncSettings#80]
Hi, I've noticed that if `SyncSettings.sublime-settings` file is pushed to github (when upload sync), it triggers a behavior in github to disable the `access_token`.

```
Hello fabioperrella,

We noticed that a valid OAuth access token of yours was committed to a public GitHub repository. Publicly disclosing a valid access token would allow other people to interact with GitHub on your behalf, potentially altering data, your contact information, and billing data.

As a precautionary measure, we have revoked the OAuth token...
```

So my suggestion is to add this file to `excluded_files` as default, or to add a warning in Readme about it.

Wdyt?

**Comment by mfuentesg** [comment]
`SyncSettings.sublime-settings`is ignored by default when uploading and downloading your settings

**Comment by fabioperrella** [comment]
But I received this email above many times when using the plugin to upload the settings. It stopped only when I added this file to `excluded_files`

**Comment by mfuentesg** [comment]
Ok, i will review this behavior

**Comment by mfuentesg** [comment]
Hey guys, I have fixed that bug [here](https://github.com/mfuentesg/SyncSettings/compare/master@%7B1548211993%7D...master)

I am preparing a new release, with a lot of fixes and improvements.

I hope, next week publish a new release.

**Comment by mfuentesg** [comment]
Fixed https://github.com/mfuentesg/SyncSettings/pull/107
