### ISSUE TITLE
Unable to sync packages

### ISSUE THREAD

**Issue by azinasili** [mfuentesg/SyncSettings#82]
I was able to setup SyncSettings on two computers without any issues. My computer at home (Mac) and my work computer (Windows). When I run `Sync Settings: Download` on the windows machine it is able to fetch my settings, however it does not sync my installed packages. I was under the impression this package would be able to do this, is there something I'm doing incorrectly?

**Comment by nahtnam** [comment]
Hey, just had the same issue but I noticed if I left sublime open for a while (around 5 minutes), everything auto installed.

**Comment by azinasili** [comment]
Guess I'll have to give it another shot

**Comment by mozhs** [comment]
@mfuentesg 

We means can this plugin sync package list ?

 It seems that you have only sync the plugin config file to gist, but we can't sync the newest packages added in another computed/platform. 

Thanks.

**Comment by mfuentesg** [comment]
Hey @mozhs, `Sync Settings` assumes that you have the latest version of your settings on `gist.github.com`.
If you  run `Download` command, and your remote settings are out of date, you local settings will be replaced by that backup.

**Comment by mfuentesg** [comment]
Btw, I am preparing a new release, with a lot of fixes and improvements.

I hope next week publish it, which includes the capability to installing packages using package control directly from SyncSettings.

**Comment by mozhs** [comment]
Wow! Sounds so good, but I'm using Atom and Visual Studio Code now hhhh😎 thanks (o.o)

**Comment by mfuentesg** [comment]
@mozhs, hahaha , me too. But, a lot of people is still using sync settings, I will give away to them , this new release :)

**Comment by mfuentesg** [comment]
Fixed https://github.com/mfuentesg/SyncSettings/pull/107
