### ISSUE TITLE
utf-8 error

### ISSUE THREAD

**Issue by SGarridoDev** [mfuentesg/SyncSettings#83]
Hi @mfuentesg,

Good work in this package. Congratulations!

I have one error when syncronize my settings with sublime text 3. Is there:

ERROR: 'utf-8' codec can't decode byte 0xf0 in position 24: invalid continuation byte

Any suggestions?

Thanks in advance

**Comment by mfuentesg** [comment]
Hey, I have fixed that bug. Check https://github.com/mfuentesg/SyncSettings/pull/107

I will try to deploy a new version the next week!

**Comment by mfuentesg** [comment]
Done https://github.com/mfuentesg/SyncSettings/pull/107
