### ISSUE TITLE
Access Token Question

### ISSUE THREAD

**Issue by bluetidepro** [mfuentesg/SyncSettings#84]
When creating the token, is only the `gist` scope the only permission needed? I didn't see anything in the docs that said.

![screen shot 2017-04-28 at 8 06 10 am](https://cloud.githubusercontent.com/assets/410701/25529897/ac93234e-2be9-11e7-9563-9f82403de8a4.png)

**Comment by mfuentesg** [comment]
Yes, it is. You don't need other permission.
