### ISSUE TITLE
Add option to exclude certain keys in certain files?

### ISSUE THREAD

**Issue by AllanLRH** [mfuentesg/SyncSettings#85]
Would be nice if it was possible to exclude certain keys in certain files... If it was just on download, that would be fine with me.

I'm using Windows and Mac, and the same font and theme settings don't render on both platforms (and screen resolutions).

Another option would be to add a hook-system, where one could add a custom python-script which manipulates a file before download or upload of it? My guess is that it would be less work for you, and provide a lot of customizability :)

**Comment by mfuentesg** [comment]
fixed https://github.com/mfuentesg/SyncSettings/pull/107
