### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by 7i4g0** [mfuentesg/SyncSettings#87]
Sync Settings: Apparently you are having problems with the internet connection.

It's probably because I have proxy.

I have try this in the User Settings file but not work: 
```
{
	"access_token": "my_token",
	"gist_id": "",
	"auto_upgrade": true,
	"proxy": "http://user:password@host:port",
}
```

How I can set proxy?

**Comment by mfuentesg** [comment]
He @7i4g0, good feedback i will consider your issue as a new feature ;)

**Comment by rdlaner** [comment]
I have the same issue. My work uses a corporate proxy which is preventing this plugin from accessing github. Would love support for adding a proxy!

**Comment by mfuentesg** [comment]
hi guys, i really sorry lately i am did very busy. I will try to do an upgrade to the plugin with all registered issues.

**Comment by mfuentesg** [comment]
Hey guys, in the next i will include this feature.
