### ISSUE TITLE
Download settings from public gist without access_token

### ISSUE THREAD

**Issue by nodkrot** [mfuentesg/SyncSettings#88]
I would like to generate a github token only for my main machine, and have all other just download the settings with gist_id? Currently it requires me to add both to download even if the gist is public.

**Comment by mfuentesg** [comment]
Thanks @nodkrot i will review this issue

**Comment by mfuentesg** [comment]
I have worked in this PR https://github.com/mfuentesg/SyncSettings/pull/107 to solve your issue.

I will try to deploy a new version the next week.

**Comment by mfuentesg** [comment]
Done https://github.com/mfuentesg/SyncSettings/pull/107
