### ISSUE TITLE
Colour scheme needs to load first

### ISSUE THREAD

**Issue by geniusupgrader** [mfuentesg/SyncSettings#90]
When "downloading" the sublime settings with SyncSettings, the colour scheme is not yet loaded and I get over 100 of these Messages: Error loading colour scheme bla bla.
And I need to click every one of them, in order to proceed to the next installation of the "downloading".
So please load the colour scheme first! It is really a design flaw.

**Comment by mmghv** [comment]
same problem here .. to overcome this I had to first copy the color scheme to sublime folder before downloading the settings .. for me I was using "SublimeLinter" package which rewrites the color scheme into its folder so I copied the "SublimeLinter" to "Packages/User" then downloaded the settings.

**Comment by mfuentesg** [comment]
Fixed https://github.com/mfuentesg/SyncSettings/pull/107
