### ISSUE TITLE
Option to check the current settings

### ISSUE THREAD

**Issue by lestevam** [mfuentesg/SyncSettings#95]
It would be possible to add a feature to check if current settings is the same in the repository. I see two possibles flows which this feature will help us.

1) We don't really know if our repository it's updated;
2) We installed/deleted a package and don't know if we sended that update for the repository;

This feature will help us not to overwrite settings by accident.

Tks!

**Comment by mfuentesg** [comment]
Hey @lestevam not sure if the current implementation of this plugin cover your request, can you please check it?

Feel free to reopen this issue.
