### ISSUE TITLE
I can't install Sync Settings via package control on sublime text 3 build 3143

### ISSUE THREAD

**Issue by arthurokonkwo** [mfuentesg/SyncSettings#98]
I followed the installation instruction at [Sync Settings package page](https://packagecontrol.io/packages/Sync%20Settings) but when select Sync setting in the list of packages to be installed, sublime will return an error in the console.
Below is the error message 

`Package Control: The dependency 'requests' is not currently installed; installing...
Package Control: The dependency 'requests' is not available
Package Control: The dependency 'requests' could not be installed or updated
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
`

Please, how do I fix this problem? 
I want to sync my settings and packages on a new computer.

**Comment by mfuentesg** [comment]
Hey @arthurokonkwo , that is not a problem of Sync Settings. Try with this solution https://github.com/wbond/package_control/issues/874#issuecomment-73521706

**Comment by Antroll** [comment]
Same as @arthurokonkwo. @mfuentesg, In this case, the Package Control is not in the ignore sheet
[screenshot](https://image.prntscr.com/image/4PqEz_UDQK_hb4ZMIoFcOA.png)

**Comment by arthurokonkwo** [comment]
Hello, @mfuentesg  I followed the link but Package Control is not on the ignore list. I re-installed Sublime and tried again, yet no solution.
So when I try o install, I get the same error.
<img width="500" alt="sync settings error" src="https://user-images.githubusercontent.com/7423077/36659296-51dbff7c-1ad4-11e8-8beb-d48e4e51eb92.PNG">

**Comment by arthurokonkwo** [comment]
I guess you may need to pay more attention to  this 

`Package Control: The dependency 'requests' is not currently installed; installing...`
`Package Control: The dependency 'requests' is not available`
`Package Control: The dependency 'requests' could not be installed or updated`

**Comment by Antroll** [comment]
So, this isn't an issue with Sync Settings—it's an issue with Package Control's ability to interface with GitHub now that GitHub has dropped support for an older cryptography method.
[wbond/package_control#1334](https://github.com/wbond/package_control/issues/1334)

**Comment by arthurokonkwo** [comment]
Finally, the problem has been fixed by [Wbond](https://github.com/wbond). I just check for sublime update and then tried installing Sync Setting via package control and it instaled successfully.
