### ISSUE TITLE
False internet connection issue

### ISSUE THREAD

**Issue by brian-k** [mfuentesg/SyncSettings#99]
I'm receiving an error from Sync Settings stating I have a problem with my internet connection, and therefore cannot upload/download my gist.  Sync Settings has worked well for me since 2015, so this is a new issue.  Package Control in Sublime Text 3 and everything else works fine when accessing the Internet.  The log for Sync Settings is empty.

I've tried to diagnose the issue, but I have been unable to find any more information or cause other than the error `Apparently you are having problems with the internet connection`.

**Comment by Derevar** [comment]
Got the same issue. But only behind our corporate firewall. It worked in the past but they changed something. (I think someting about the handling of encrypted traffic)
The thing is, settings sync for VS Code works flawlessly from here still. (https://github.com/shanalikhan/code-settings-sync)

Maybe this can help figure it out.

**Comment by brian-k** [comment]
I don't have problems with VS Code, but I think that sync extension is from another author.  I am not behind a corporate firewall and the issue occurs regardless of the type of connection (home, corporate, tethered phone).

**Comment by Derevar** [comment]
The hint with the VS Code extension was more meant for the developers of this sync solution here.
There could be a problem with how the github api is implemented or something like that.

But maybe the problems are not related after all. Under normal home-like circumstanced it works perfectly fine for me.

**Comment by Derevar** [comment]
I've tried myself in debugging this plugin and at least my issue is "solved". It is indeed the certificate.
![settings_syn](https://user-images.githubusercontent.com/657768/37200093-10436880-2384-11e8-8ae8-019f8950b286.png)

If one would like to ignore the certificates he could change:
`response = requests.get(self.BASE_URL + '/user?access_token=' + token)`
to
`response = requests.get(self.BASE_URL + '/user?access_token=' + token, verify=False)`
in
`Sync Settings\sync_settings\gist_api.py`

That quick&dirty fix should make it work. But I would strongly advice against it.

But maybe adding the code you see in the screenshot could help you figuring out your problem @brian-k.
